services:
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  database_admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=admin@hirasawa.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5050:5050"
    depends_on:
      - database
networks:
  default:
    name: hi-backend